export const Exercises = {
  chest: [
    { name: "Bench Press", type: "weighted" },
    { name: "Incline Bench Press", type: "weighted" },
    { name: "Decline Bench Press", type: "weighted" },
    { name: "Dumbbell Fly", type: "weighted" },
    { name: "Cable Fly", type: "weighted" },
    { name: "Push Up", type: "bodyweight" },
    { name: "Incline Push Up", type: "bodyweight" },
    { name: "Decline Push Up", type: "bodyweight" },
    { name: "Chest Dip", type: "bodyweight" },
    { name: "Pec Deck", type: "weighted" },
    { name: "Landmine Press", type: "weighted" },
    { name: "Low Cable Fly", type: "weighted" },
    { name: "High Cable Fly", type: "weighted" },
    { name: "Dumbbell Press", type: "weighted" },
    { name: "Incline Dumbbell Press", type: "weighted" },
    { name: "Decline Dumbbell Press", type: "weighted" },
    { name: "Incline Dumbbell Fly", type: "weighted" },
    { name: "Smith Machine Bench Press", type: "weighted" },
    { name: "Smith Machine Incline Press", type: "weighted" },
    { name: "Svend Press", type: "weighted" },
    { name: "Chest Press Machine", type: "weighted" },
    { name: "Incline Cable Press", type: "weighted" },
    { name: "Decline Cable Press", type: "weighted" },
    { name: "Wide Push Up", type: "bodyweight" },
    { name: "Archer Push Up", type: "bodyweight" },
    { name: "Pike Push Up", type: "bodyweight" },
    { name: "Clap Push Up", type: "bodyweight" },
    { name: "Pseudo Planche Push Up", type: "bodyweight" },
    { name: "Ring Push Up", type: "bodyweight" },
    { name: "Banded Chest Fly", type: "weighted" },
    { name: "Banded Push Up", type: "bodyweight" },
    { name: "Floor Press", type: "weighted" },
    { name: "Dumbbell Pullover", type: "weighted" },
    { name: "Cable Pullover", type: "weighted" },
    { name: "Hex Press", type: "weighted" },
    { name: "Squeeze Press", type: "weighted" },
    { name: "Single Arm Cable Fly", type: "weighted" },
    { name: "Single Arm Dumbbell Press", type: "weighted" },
    { name: "Resistance Band Push Up", type: "bodyweight" },
    { name: "TRX Push Up", type: "bodyweight" },
    { name: "TRX Fly", type: "bodyweight" },
    { name: "Medicine Ball Push Up", type: "bodyweight" },
    { name: "Close Grip Push Up", type: "bodyweight" },
    { name: "Staggered Push Up", type: "bodyweight" },
    { name: "Weighted Push Up", type: "weighted" },
    { name: "Chest Squeeze", type: "weighted" },
    { name: "Cable Crossover", type: "weighted" },
    { name: "Reverse Grip Bench Press", type: "weighted" },
    { name: "Guillotine Press", type: "weighted" },
    { name: "Dip Machine", type: "weighted" },
    // New additions
    { name: "Kettlebell Floor Press", type: "weighted" },
    { name: "Alternating Dumbbell Press", type: "weighted" },
    { name: "Single Arm Floor Press", type: "weighted" },
    { name: "Incline Hex Press", type: "weighted" },
    { name: "Decline Fly", type: "weighted" },
    { name: "Decline Cable Fly", type: "weighted" },
    { name: "Smith Machine Decline Press", type: "weighted" },
    { name: "Plate Press", type: "weighted" },
    { name: "Plyometric Push Up", type: "bodyweight" },
    { name: "One Arm Push Up", type: "bodyweight" },
    { name: "Superman Push Up", type: "bodyweight" },
    { name: "Typewriter Push Up", type: "bodyweight" },
    { name: "Hindu Push Up", type: "bodyweight" },
    { name: "Diamond Push Up", type: "bodyweight" },
    { name: "Spiderman Push Up", type: "bodyweight" },
    { name: "T Push Up", type: "bodyweight" },
    { name: "Barbell Pullover", type: "weighted" },
    { name: "Low to High Cable Fly", type: "weighted" },
    { name: "High to Low Cable Fly", type: "weighted" },
    { name: "Neutral Grip Dumbbell Press", type: "weighted" },
    { name: "Rotating Dumbbell Press", type: "weighted" },
    { name: "Dumbbell Around the World", type: "weighted" },
    { name: "Pause Bench Press", type: "weighted" },
    { name: "Tempo Bench Press", type: "weighted" },
    { name: "Pin Press", type: "weighted" },
    { name: "Board Press", type: "weighted" },
    { name: "Swiss Bar Bench Press", type: "weighted" },
    { name: "Dumbbell Squeeze Press", type: "weighted" },
    { name: "Incline Squeeze Press", type: "weighted" },
  ],
  back: [
    { name: "Deadlift", type: "weighted" },
    { name: "Barbell Row", type: "weighted" },
    { name: "Dumbbell Row", type: "weighted" },
    { name: "Lat Pulldown", type: "weighted" },
    { name: "Seated Cable Row", type: "weighted" },
    { name: "Pull Up", type: "bodyweight" },
    { name: "Chin Up", type: "bodyweight" },
    { name: "T-Bar Row", type: "weighted" },
    { name: "Face Pull", type: "weighted" },
    { name: "Hyperextension", type: "weighted" },
    { name: "Rack Pull", type: "weighted" },
    { name: "Sumo Deadlift", type: "weighted" },
    { name: "Romanian Deadlift", type: "weighted" },
    { name: "Single Arm Dumbbell Row", type: "weighted" },
    { name: "Pendlay Row", type: "weighted" },
    { name: "Meadows Row", type: "weighted" },
    { name: "Chest Supported Row", type: "weighted" },
    { name: "Machine Row", type: "weighted" },
    { name: "Wide Grip Lat Pulldown", type: "weighted" },
    { name: "Close Grip Lat Pulldown", type: "weighted" },
    { name: "Straight Arm Pulldown", type: "weighted" },
    { name: "Single Arm Lat Pulldown", type: "weighted" },
    { name: "Cable Row", type: "weighted" },
    { name: "High Row", type: "weighted" },
    { name: "Low Row", type: "weighted" },
    { name: "Inverted Row", type: "bodyweight" },
    { name: "Australian Pull Up", type: "bodyweight" },
    { name: "Neutral Grip Pull Up", type: "bodyweight" },
    { name: "Wide Grip Pull Up", type: "bodyweight" },
    { name: "Weighted Pull Up", type: "weighted" },
    { name: "Weighted Chin Up", type: "weighted" },
    { name: "Jefferson Curl", type: "weighted" },
    { name: "Good Morning", type: "weighted" },
    { name: "Back Extension", type: "bodyweight" },
    { name: "Reverse Hyperextension", type: "weighted" },
    { name: "Barbell Shrug", type: "weighted" },
    { name: "Dumbbell Shrug", type: "weighted" },
    { name: "Cable Shrug", type: "weighted" },
    { name: "Trap Bar Deadlift", type: "weighted" },
    { name: "Single Leg Deadlift", type: "weighted" },
    { name: "Landmine Row", type: "weighted" },
    { name: "Banded Pull Apart", type: "weighted" },
    { name: "TRX Row", type: "bodyweight" },
    { name: "Ring Row", type: "bodyweight" },
    { name: "Seal Row", type: "weighted" },
    { name: "Dumbbell Pullover", type: "weighted" },
    { name: "Straight Arm Cable Row", type: "weighted" },
    { name: "Kneeling Cable Row", type: "weighted" },
    { name: "Smith Machine Row", type: "weighted" },
    { name: "Deficit Deadlift", type: "weighted" },
    // New additions
    { name: "Snatch Grip Deadlift", type: "weighted" },
    { name: "Banded Deadlift", type: "weighted" },
    { name: "Pause Deadlift", type: "weighted" },
    { name: "Touch and Go Deadlift", type: "weighted" },
    { name: "Block Pull", type: "weighted" },
    { name: "Cable Pull Through", type: "weighted" },
    { name: "Stiff Arm Pulldown", type: "weighted" },
    { name: "Underhand Barbell Row", type: "weighted" },
    { name: "Kroc Row", type: "weighted" },
    { name: "Helms Row", type: "weighted" },
    { name: "Cable Pullover", type: "weighted" },
    { name: "Banded Pull Down", type: "weighted" },
    { name: "Rope Straight Arm Pulldown", type: "weighted" },
    { name: "Single Arm Cable Row", type: "weighted" },
    { name: "Supinated Lat Pulldown", type: "weighted" },
    { name: "Behind the Neck Pulldown", type: "weighted" },
    { name: "Incline Dumbbell Row", type: "weighted" },
    { name: "Prone Dumbbell Row", type: "weighted" },
    { name: "Resistance Band Row", type: "weighted" },
    { name: "Resistance Band Pull Apart", type: "weighted" },
    { name: "Resistance Band Lat Pulldown", type: "weighted" },
    { name: "Close Grip Pull Up", type: "bodyweight" },
    { name: "L Sit Pull Up", type: "bodyweight" },
    { name: "Commando Pull Up", type: "bodyweight" },
    { name: "Archer Pull Up", type: "bodyweight" },
    { name: "Muscle Up", type: "bodyweight" },
    { name: "Typewriter Pull Up", type: "bodyweight" },
    { name: "Scapular Pull Up", type: "bodyweight" },
    { name: "Dead Hang", type: "duration" },
    { name: "Active Hang", type: "duration" },
    { name: "Hip Hinge", type: "bodyweight" },
    { name: "Trap Bar Shrug", type: "weighted" },
  ],
  shoulders: [
    { name: "Overhead Press", type: "weighted" },
    { name: "Dumbbell Shoulder Press", type: "weighted" },
    { name: "Lateral Raise", type: "weighted" },
    { name: "Front Raise", type: "weighted" },
    { name: "Rear Delt Fly", type: "weighted" },
    { name: "Arnold Press", type: "weighted" },
    { name: "Cable Lateral Raise", type: "weighted" },
    { name: "Upright Row", type: "weighted" },
    { name: "Shrug", type: "weighted" },
    { name: "Face Pull", type: "weighted" },
    { name: "Push Press", type: "weighted" },
    { name: "Behind the Neck Press", type: "weighted" },
    { name: "Z Press", type: "weighted" },
    { name: "Seated Dumbbell Press", type: "weighted" },
    { name: "Single Arm Dumbbell Press", type: "weighted" },
    { name: "Single Arm Cable Press", type: "weighted" },
    { name: "Landmine Press", type: "weighted" },
    { name: "Landmine Lateral Raise", type: "weighted" },
    { name: "Cable Front Raise", type: "weighted" },
    { name: "Cable Rear Delt Fly", type: "weighted" },
    { name: "Bent Over Lateral Raise", type: "weighted" },
    { name: "Incline Lateral Raise", type: "weighted" },
    { name: "Prone Rear Delt Raise", type: "weighted" },
    { name: "Machine Shoulder Press", type: "weighted" },
    { name: "Machine Lateral Raise", type: "weighted" },
    { name: "Machine Rear Delt Fly", type: "weighted" },
    { name: "Barbell Front Raise", type: "weighted" },
    { name: "Plate Front Raise", type: "weighted" },
    { name: "Dumbbell Upright Row", type: "weighted" },
    { name: "Cable Upright Row", type: "weighted" },
    { name: "Pike Push Up", type: "bodyweight" },
    { name: "Handstand Push Up", type: "bodyweight" },
    { name: "Wall Handstand Hold", type: "duration" },
    { name: "Band Pull Apart", type: "weighted" },
    { name: "Band Dislocate", type: "weighted" },
    { name: "Bottoms Up Press", type: "weighted" },
    { name: "Kettlebell Press", type: "weighted" },
    { name: "Kettlebell Swing", type: "weighted" },
    { name: "High Pull", type: "weighted" },
    { name: "Power Clean", type: "weighted" },
    { name: "Snatch", type: "weighted" },
    { name: "Bradford Press", type: "weighted" },
    { name: "Cuban Press", type: "weighted" },
    { name: "Scarecrow", type: "weighted" },
    { name: "YTW Raise", type: "weighted" },
    { name: "Dumbbell Shrug", type: "weighted" },
    { name: "Trap Bar Shrug", type: "weighted" },
    { name: "Smith Machine Overhead Press", type: "weighted" },
    { name: "Seated Behind Neck Press", type: "weighted" },
    { name: "Single Arm Lateral Raise", type: "weighted" },
    // New additions
    { name: "Leaning Lateral Raise", type: "weighted" },
    { name: "Cross Body Lateral Raise", type: "weighted" },
    { name: "Kelso Shrug", type: "weighted" },
    { name: "Cable Y Raise", type: "weighted" },
    { name: "Cable T Raise", type: "weighted" },
    { name: "Cable W Raise", type: "weighted" },
    { name: "Dumbbell W Raise", type: "weighted" },
    { name: "Dumbbell L Raise", type: "weighted" },
    { name: "Dumbbell T Raise", type: "weighted" },
    { name: "Dumbbell Y Raise", type: "weighted" },
    { name: "Seated Lateral Raise", type: "weighted" },
    { name: "Behind the Back Cable Raise", type: "weighted" },
    { name: "Rope Face Pull", type: "weighted" },
    { name: "Jammer Press", type: "weighted" },
    { name: "Viking Press", type: "weighted" },
    { name: "Klokov Press", type: "weighted" },
    { name: "Dumbbell Halo", type: "weighted" },
    { name: "Barbell Halo", type: "weighted" },
    { name: "Plate Halo", type: "weighted" },
    { name: "Single Arm Upright Row", type: "weighted" },
    { name: "Dumbbell External Rotation", type: "weighted" },
    { name: "Cable External Rotation", type: "weighted" },
    { name: "Cable Internal Rotation", type: "weighted" },
    { name: "Lying Rear Delt Raise", type: "weighted" },
    { name: "Seated Rear Delt Raise", type: "weighted" },
    { name: "Handstand Hold", type: "duration" },
    { name: "Pike Hold", type: "duration" },
    { name: "Resistance Band Overhead Press", type: "weighted" },
    { name: "Resistance Band Lateral Raise", type: "weighted" },
    { name: "Resistance Band Front Raise", type: "weighted" },
    { name: "Resistance Band Face Pull", type: "weighted" },
  ],
  arms: [
    { name: "Barbell Curl", type: "weighted" },
    { name: "Dumbbell Curl", type: "weighted" },
    { name: "Hammer Curl", type: "weighted" },
    { name: "Preacher Curl", type: "weighted" },
    { name: "Cable Curl", type: "weighted" },
    { name: "Tricep Pushdown", type: "weighted" },
    { name: "Skull Crusher", type: "weighted" },
    { name: "Overhead Tricep Extension", type: "weighted" },
    { name: "Diamond Push Up", type: "bodyweight" },
    { name: "Dip", type: "bodyweight" },
    { name: "Close Grip Bench Press", type: "weighted" },
    { name: "Concentration Curl", type: "weighted" },
    { name: "Incline Dumbbell Curl", type: "weighted" },
    { name: "Spider Curl", type: "weighted" },
    { name: "Zottman Curl", type: "weighted" },
    { name: "Reverse Curl", type: "weighted" },
    { name: "Cable Hammer Curl", type: "weighted" },
    { name: "Cable Rope Curl", type: "weighted" },
    { name: "EZ Bar Curl", type: "weighted" },
    { name: "EZ Bar Preacher Curl", type: "weighted" },
    { name: "Machine Curl", type: "weighted" },
    { name: "Single Arm Cable Curl", type: "weighted" },
    { name: "21s Curl", type: "weighted" },
    { name: "Drag Curl", type: "weighted" },
    { name: "Waiter Curl", type: "weighted" },
    { name: "Cross Body Hammer Curl", type: "weighted" },
    { name: "Rope Overhead Tricep Extension", type: "weighted" },
    { name: "Single Arm Tricep Pushdown", type: "weighted" },
    { name: "Tricep Kickback", type: "weighted" },
    { name: "Cable Tricep Kickback", type: "weighted" },
    { name: "Bench Dip", type: "bodyweight" },
    { name: "Weighted Dip", type: "weighted" },
    { name: "JM Press", type: "weighted" },
    { name: "Tate Press", type: "weighted" },
    { name: "Rolling Tricep Extension", type: "weighted" },
    { name: "Single Arm Overhead Extension", type: "weighted" },
    { name: "Reverse Grip Tricep Pushdown", type: "weighted" },
    { name: "Wrist Curl", type: "weighted" },
    { name: "Reverse Wrist Curl", type: "weighted" },
    { name: "Farmers Carry", type: "weighted" },
    { name: "Plate Pinch", type: "duration" },
    { name: "Dead Hang", type: "duration" },
    { name: "Chin Up", type: "bodyweight" },
    { name: "Neutral Grip Chin Up", type: "bodyweight" },
    { name: "Ring Curl", type: "bodyweight" },
    { name: "Ring Dip", type: "bodyweight" },
    { name: "Bayesian Curl", type: "weighted" },
    { name: "Poliquin Raise", type: "weighted" },
    { name: "Band Curl", type: "weighted" },
    { name: "Band Tricep Pushdown", type: "weighted" },
    // New additions
    { name: "Alternating Dumbbell Curl", type: "weighted" },
    { name: "Seated Dumbbell Curl", type: "weighted" },
    { name: "Standing Barbell Curl", type: "weighted" },
    { name: "Wide Grip Barbell Curl", type: "weighted" },
    { name: "Narrow Grip Barbell Curl", type: "weighted" },
    { name: "Prone Incline Curl", type: "weighted" },
    { name: "High Cable Curl", type: "weighted" },
    { name: "Low Cable Curl", type: "weighted" },
    { name: "Machine Preacher Curl", type: "weighted" },
    { name: "Dumbbell Preacher Curl", type: "weighted" },
    { name: "Scott Curl", type: "weighted" },
    { name: "Cable Concentration Curl", type: "weighted" },
    { name: "Supinated Cable Curl", type: "weighted" },
    { name: "Reverse EZ Bar Curl", type: "weighted" },
    { name: "Pinwheel Curl", type: "weighted" },
    { name: "Dumbbell Twist Curl", type: "weighted" },
    { name: "Overhead Cable Curl", type: "weighted" },
    { name: "Behind the Back Barbell Curl", type: "weighted" },
    { name: "Cable Overhead Tricep Extension", type: "weighted" },
    { name: "Dumbbell Skull Crusher", type: "weighted" },
    { name: "EZ Bar Skull Crusher", type: "weighted" },
    { name: "Cable Skull Crusher", type: "weighted" },
    { name: "Single Arm Cable Kickback", type: "weighted" },
    { name: "Dumbbell Tricep Kickback", type: "weighted" },
    { name: "Smith Machine Close Grip Press", type: "weighted" },
    { name: "Banded Tricep Pushdown", type: "weighted" },
    { name: "Banded Bicep Curl", type: "weighted" },
    { name: "Towel Chin Up", type: "bodyweight" },
    { name: "Close Grip Chin Up", type: "bodyweight" },
    { name: "Parallel Bar Tricep Dip", type: "bodyweight" },
    { name: "Straight Bar Dip", type: "bodyweight" },
    { name: "Behind the Back Wrist Curl", type: "weighted" },
    { name: "Plate Wrist Curl", type: "weighted" },
    { name: "Forearm Roller", type: "weighted" },
    { name: "Grip Squeeze", type: "duration" },
    { name: "Towel Row", type: "bodyweight" },
  ],
  legs: [
    { name: "Squat", type: "weighted" },
    { name: "Front Squat", type: "weighted" },
    { name: "Leg Press", type: "weighted" },
    { name: "Romanian Deadlift", type: "weighted" },
    { name: "Bulgarian Split Squat", type: "weighted" },
    { name: "Lunge", type: "weighted" },
    { name: "Leg Curl", type: "weighted" },
    { name: "Leg Extension", type: "weighted" },
    { name: "Calf Raise", type: "weighted" },
    { name: "Hack Squat", type: "weighted" },
    { name: "Glute Bridge", type: "weighted" },
    { name: "Hip Thrust", type: "weighted" },
    { name: "Sumo Squat", type: "weighted" },
    { name: "Goblet Squat", type: "weighted" },
    { name: "Box Squat", type: "weighted" },
    { name: "Pause Squat", type: "weighted" },
    { name: "Zercher Squat", type: "weighted" },
    { name: "Safety Bar Squat", type: "weighted" },
    { name: "Smith Machine Squat", type: "weighted" },
    { name: "Pistol Squat", type: "bodyweight" },
    { name: "Jump Squat", type: "bodyweight" },
    { name: "Wall Sit", type: "duration" },
    { name: "Step Up", type: "weighted" },
    { name: "Reverse Lunge", type: "weighted" },
    { name: "Walking Lunge", type: "weighted" },
    { name: "Lateral Lunge", type: "weighted" },
    { name: "Curtsy Lunge", type: "weighted" },
    { name: "Nordic Curl", type: "bodyweight" },
    { name: "Seated Leg Curl", type: "weighted" },
    { name: "Lying Leg Curl", type: "weighted" },
    { name: "Standing Leg Curl", type: "weighted" },
    { name: "Seated Calf Raise", type: "weighted" },
    { name: "Donkey Calf Raise", type: "weighted" },
    { name: "Single Leg Calf Raise", type: "weighted" },
    { name: "Leg Press Calf Raise", type: "weighted" },
    { name: "Stiff Leg Deadlift", type: "weighted" },
    { name: "Single Leg Deadlift", type: "weighted" },
    { name: "Good Morning", type: "weighted" },
    { name: "Kettlebell Swing", type: "weighted" },
    { name: "Hip Abduction", type: "weighted" },
    { name: "Hip Adduction", type: "weighted" },
    { name: "Cable Kickback", type: "weighted" },
    { name: "Donkey Kick", type: "bodyweight" },
    { name: "Fire Hydrant", type: "bodyweight" },
    { name: "Frog Pump", type: "bodyweight" },
    { name: "Single Leg Hip Thrust", type: "weighted" },
    { name: "Trap Bar Deadlift", type: "weighted" },
    { name: "Sled Push", type: "weighted" },
    { name: "Sled Pull", type: "weighted" },
    { name: "Box Jump", type: "bodyweight" },
    // New additions
    { name: "Heel Elevated Squat", type: "weighted" },
    { name: "Narrow Stance Squat", type: "weighted" },
    { name: "Wide Stance Squat", type: "weighted" },
    { name: "Overhead Squat", type: "weighted" },
    { name: "Anderson Squat", type: "weighted" },
    { name: "Tempo Squat", type: "weighted" },
    { name: "Banded Squat", type: "weighted" },
    { name: "Dumbbell Squat", type: "weighted" },
    { name: "Landmine Squat", type: "weighted" },
    { name: "Leg Press Single Leg", type: "weighted" },
    { name: "Sissy Squat", type: "bodyweight" },
    { name: "Bodyweight Squat", type: "bodyweight" },
    { name: "Split Squat", type: "weighted" },
    { name: "Rear Foot Elevated Split Squat", type: "weighted" },
    { name: "Dumbbell Bulgarian Split Squat", type: "weighted" },
    { name: "Dumbbell Lunge", type: "weighted" },
    { name: "Dumbbell Reverse Lunge", type: "weighted" },
    { name: "Dumbbell Walking Lunge", type: "weighted" },
    { name: "Barbell Lunge", type: "weighted" },
    { name: "Barbell Reverse Lunge", type: "weighted" },
    { name: "Deficit Lunge", type: "weighted" },
    { name: "Elevated Glute Bridge", type: "weighted" },
    { name: "Banded Glute Bridge", type: "weighted" },
    { name: "Banded Hip Thrust", type: "weighted" },
    { name: "Cable Hip Thrust", type: "weighted" },
    { name: "Machine Hip Thrust", type: "weighted" },
    { name: "45 Degree Back Extension", type: "weighted" },
    { name: "GHD Hyperextension", type: "weighted" },
    { name: "Cable Hip Abduction", type: "weighted" },
    { name: "Cable Hip Adduction", type: "weighted" },
    { name: "Machine Hip Abduction", type: "weighted" },
    { name: "Machine Hip Adduction", type: "weighted" },
    { name: "Banded Hip Abduction", type: "weighted" },
    { name: "Banded Glute Kickback", type: "weighted" },
    { name: "Dumbbell Step Up", type: "weighted" },
    { name: "Lateral Step Up", type: "weighted" },
    { name: "Deficit Split Squat", type: "weighted" },
    { name: "Tib Raise", type: "bodyweight" },
    { name: "Tibialis Raise", type: "weighted" },
    { name: "Ankle Dorsiflexion", type: "bodyweight" },
    { name: "Standing Hip Flexion", type: "weighted" },
    { name: "Cable Pull Through", type: "weighted" },
    { name: "Single Leg Press", type: "weighted" },
    { name: "Leg Press Hack Squat", type: "weighted" },
    { name: "Lying Hip Abduction", type: "bodyweight" },
    { name: "Clam Shell", type: "bodyweight" },
    { name: "Monster Walk", type: "weighted" },
    { name: "Lateral Band Walk", type: "weighted" },
    { name: "Glute March", type: "bodyweight" },
    { name: "Reverse Hyperextension", type: "weighted" },
    { name: "Prone Hamstring Curl", type: "bodyweight" },
    { name: "Depth Jump", type: "bodyweight" },
    { name: "Broad Jump", type: "bodyweight" },
    { name: "Lateral Jump", type: "bodyweight" },
  ],
  core: [
    { name: "Plank", type: "duration" },
    { name: "Side Plank", type: "duration" },
    { name: "Hollow Hold", type: "duration" },
    { name: "Dead Bug", type: "bodyweight" },
    { name: "Crunch", type: "bodyweight" },
    { name: "Sit Up", type: "bodyweight" },
    { name: "Leg Raise", type: "bodyweight" },
    { name: "Russian Twist", type: "bodyweight" },
    { name: "Ab Wheel Rollout", type: "bodyweight" },
    { name: "Cable Crunch", type: "weighted" },
    { name: "Hanging Leg Raise", type: "bodyweight" },
    { name: "Mountain Climber", type: "duration" },
    { name: "V Up", type: "bodyweight" },
    { name: "Toes to Bar", type: "bodyweight" },
    { name: "Knees to Chest", type: "bodyweight" },
    { name: "Reverse Crunch", type: "bodyweight" },
    { name: "Bicycle Crunch", type: "bodyweight" },
    { name: "Flutter Kick", type: "duration" },
    { name: "Scissor Kick", type: "bodyweight" },
    { name: "Dragon Flag", type: "bodyweight" },
    { name: "L Sit", type: "duration" },
    { name: "Front Lever", type: "duration" },
    { name: "Pallof Press", type: "weighted" },
    { name: "Cable Wood Chop", type: "weighted" },
    { name: "Landmine Rotation", type: "weighted" },
    { name: "Weighted Crunch", type: "weighted" },
    { name: "Weighted Sit Up", type: "weighted" },
    { name: "Weighted Russian Twist", type: "weighted" },
    { name: "Decline Sit Up", type: "bodyweight" },
    { name: "Decline Crunch", type: "bodyweight" },
    { name: "Incline Leg Raise", type: "bodyweight" },
    { name: "Hanging Knee Raise", type: "bodyweight" },
    { name: "Roman Chair Sit Up", type: "bodyweight" },
    { name: "GHD Sit Up", type: "bodyweight" },
    { name: "Hyperextension", type: "weighted" },
    { name: "Back Extension", type: "bodyweight" },
    { name: "Bird Dog", type: "duration" },
    { name: "Bear Crawl", type: "duration" },
    { name: "Suitcase Carry", type: "weighted" },
    { name: "Farmers Carry", type: "weighted" },
    { name: "Overhead Carry", type: "weighted" },
    { name: "Copenhagen Plank", type: "duration" },
    { name: "Stir the Pot", type: "duration" },
    { name: "Ab Crunch Machine", type: "weighted" },
    { name: "Rotary Torso Machine", type: "weighted" },
    { name: "TRX Plank", type: "duration" },
    { name: "TRX Pike", type: "bodyweight" },
    { name: "TRX Rollout", type: "bodyweight" },
    { name: "Windmill", type: "weighted" },
    { name: "Turkish Get Up", type: "weighted" },
    // New additions
    { name: "Plank to Push Up", type: "bodyweight" },
    { name: "Plank Hip Dip", type: "bodyweight" },
    { name: "Plank Shoulder Tap", type: "bodyweight" },
    { name: "Plank Knee to Elbow", type: "bodyweight" },
    { name: "Plank Reach", type: "bodyweight" },
    { name: "Plank with Leg Lift", type: "bodyweight" },
    { name: "Side Plank Hip Dip", type: "bodyweight" },
    { name: "Side Plank with Rotation", type: "bodyweight" },
    { name: "Side Plank Raise", type: "bodyweight" },
    { name: "RKC Plank", type: "duration" },
    { name: "Hollow Body Rock", type: "bodyweight" },
    { name: "Arch Body Hold", type: "duration" },
    { name: "Arch Body Rock", type: "bodyweight" },
    { name: "Hollow Body Hold", type: "duration" },
    { name: "Tuck Hold", type: "duration" },
    { name: "Hanging Windshield Wiper", type: "bodyweight" },
    { name: "Hanging Side Knee Raise", type: "bodyweight" },
    { name: "Cable Oblique Crunch", type: "weighted" },
    { name: "Barbell Rollout", type: "weighted" },
    { name: "Kneeling Ab Wheel Rollout", type: "bodyweight" },
    { name: "Dragon Flag Negative", type: "bodyweight" },
    { name: "Tuck Front Lever", type: "duration" },
    { name: "Half Lay Front Lever", type: "duration" },
    { name: "Tuck L Sit", type: "duration" },
    { name: "Pallof Press Hold", type: "duration" },
    { name: "Pallof Press Walk", type: "weighted" },
    { name: "Half Kneeling Pallof Press", type: "weighted" },
    { name: "Cable High to Low Chop", type: "weighted" },
    { name: "Cable Low to High Chop", type: "weighted" },
    { name: "Dumbbell Wood Chop", type: "weighted" },
    { name: "Banded Wood Chop", type: "weighted" },
    { name: "Landmine Anti-Rotation", type: "weighted" },
    { name: "Sandbag Carry", type: "weighted" },
    { name: "Waiter Carry", type: "weighted" },
    { name: "Zercher Carry", type: "weighted" },
    { name: "Single Arm Overhead Carry", type: "weighted" },
    { name: "Suitcase Deadlift", type: "weighted" },
    { name: "Offset Squat", type: "weighted" },
    { name: "Renegade Row", type: "weighted" },
    { name: "Dumbbell Plank Row", type: "weighted" },
    { name: "Ab Bicycle", type: "bodyweight" },
    { name: "Toe Touch Crunch", type: "bodyweight" },
    { name: "Heel Touch", type: "bodyweight" },
    { name: "Cross Crunch", type: "bodyweight" },
    { name: "Seated Leg Tuck", type: "bodyweight" },
    { name: "Seated Knee Tuck", type: "bodyweight" },
  ],
  cardio: [
    { name: "Treadmill Run", type: "duration" },
    { name: "Cycling", type: "duration" },
    { name: "Rowing Machine", type: "duration" },
    { name: "Jump Rope", type: "duration" },
    { name: "Stair Climber", type: "duration" },
    { name: "Elliptical", type: "duration" },
    { name: "Battle Ropes", type: "duration" },
    { name: "Burpee", type: "bodyweight" },
    { name: "Box Jump", type: "bodyweight" },
    { name: "Sled Push", type: "duration" },
    { name: "Sprint", type: "duration" },
    { name: "Hill Sprint", type: "duration" },
    { name: "Incline Treadmill Walk", type: "duration" },
    { name: "Assault Bike", type: "duration" },
    { name: "Ski Erg", type: "duration" },
    { name: "Versa Climber", type: "duration" },
    { name: "Swimming", type: "duration" },
    { name: "Jump Squat", type: "bodyweight" },
    { name: "High Knees", type: "duration" },
    { name: "Butt Kicks", type: "duration" },
    { name: "Jumping Jack", type: "duration" },
    { name: "Star Jump", type: "bodyweight" },
    { name: "Tuck Jump", type: "bodyweight" },
    { name: "Broad Jump", type: "bodyweight" },
    { name: "Lateral Bound", type: "bodyweight" },
    { name: "Single Leg Hop", type: "bodyweight" },
    { name: "Kettlebell Swing", type: "weighted" },
    { name: "Kettlebell Snatch", type: "weighted" },
    { name: "Kettlebell Clean", type: "weighted" },
    { name: "Medicine Ball Slam", type: "weighted" },
    { name: "Wall Ball", type: "weighted" },
    { name: "Tire Flip", type: "weighted" },
    { name: "Farmer Carry", type: "weighted" },
    { name: "Sandbag Carry", type: "weighted" },
    { name: "Bear Crawl", type: "duration" },
    { name: "Crab Walk", type: "duration" },
    { name: "Lateral Shuffle", type: "duration" },
    { name: "Agility Ladder", type: "duration" },
    { name: "Cone Drill", type: "duration" },
    { name: "Sled Pull", type: "duration" },
    { name: "Prowler Push", type: "duration" },
    { name: "Rower Sprint", type: "duration" },
    { name: "Bike Sprint", type: "duration" },
    { name: "Swimming Sprint", type: "duration" },
    { name: "Step Up", type: "bodyweight" },
    { name: "Skater Jump", type: "bodyweight" },
    { name: "Speed Skater", type: "duration" },
    { name: "Inchworm", type: "bodyweight" },
    { name: "Jumping Lunge", type: "bodyweight" },
    { name: "Power Skip", type: "duration" },
    // New additions
    { name: "Treadmill Walk", type: "duration" },
    { name: "Treadmill Interval Run", type: "duration" },
    { name: "Outdoor Run", type: "duration" },
    { name: "Trail Run", type: "duration" },
    { name: "Tempo Run", type: "duration" },
    { name: "Fartlek Run", type: "duration" },
    { name: "Stationary Bike", type: "duration" },
    { name: "Spin Bike", type: "duration" },
    { name: "Recumbent Bike", type: "duration" },
    { name: "Hand Bike", type: "duration" },
    { name: "Ergometer Row", type: "duration" },
    { name: "Cable Machine Row Sprint", type: "duration" },
    { name: "Double Under", type: "bodyweight" },
    { name: "Single Under", type: "bodyweight" },
    { name: "Weighted Jump Rope", type: "weighted" },
    { name: "Burpee Box Jump", type: "bodyweight" },
    { name: "Burpee Pull Up", type: "bodyweight" },
    { name: "Burpee Broad Jump", type: "bodyweight" },
    { name: "Kettlebell Turkish Get Up", type: "weighted" },
    { name: "Kettlebell Goblet Squat", type: "weighted" },
    { name: "Kettlebell Clean and Press", type: "weighted" },
    { name: "Kettlebell Windmill", type: "weighted" },
    { name: "Medicine Ball Chest Pass", type: "weighted" },
    { name: "Medicine Ball Overhead Slam", type: "weighted" },
    { name: "Medicine Ball Rotational Throw", type: "weighted" },
    { name: "Sandbag Squat", type: "weighted" },
    { name: "Sandbag Shouldering", type: "weighted" },
    { name: "Sandbag Throw", type: "weighted" },
    { name: "Rope Climb", type: "bodyweight" },
    { name: "Rope Climb (Legless)", type: "bodyweight" },
    { name: "Monkey Bars", type: "bodyweight" },
    { name: "Ring Muscle Up", type: "bodyweight" },
    { name: "Bar Muscle Up", type: "bodyweight" },
    { name: "Thruster", type: "weighted" },
    { name: "Power Snatch", type: "weighted" },
    { name: "Hang Power Clean", type: "weighted" },
    { name: "Clean and Jerk", type: "weighted" },
    { name: "Box Step Up Run", type: "duration" },
    { name: "Shuttle Run", type: "duration" },
    { name: "Suicide Run", type: "duration" },
    { name: "Parachute Sprint", type: "duration" },
    { name: "Hill Walk", type: "duration" },
    { name: "Stair Run", type: "duration" },
    { name: "Stair Walk", type: "duration" },
    { name: "Swimming Freestyle", type: "duration" },
    { name: "Swimming Backstroke", type: "duration" },
    { name: "Swimming Breaststroke", type: "duration" },
    { name: "Swimming Butterfly", type: "duration" },
    { name: "Water Polo Treading", type: "duration" },
    { name: "Kickboxing", type: "duration" },
    { name: "Shadow Boxing", type: "duration" },
    { name: "Heavy Bag", type: "duration" },
    { name: "Speed Bag", type: "duration" },
    { name: "Jump Rope Double Under", type: "duration" },
  ],
};
