/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeightIndexRouteImport } from './routes/weight/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as FoodIndexRouteImport } from './routes/food/index'
import { Route as ScheduleCreateRouteImport } from './routes/schedule/create'
import { Route as FoodFoodIdRouteImport } from './routes/food/$foodId'
import { Route as ScheduleScheduleIdIndexRouteImport } from './routes/schedule/$scheduleId/index'
import { Route as ScheduleScheduleIdStartRouteImport } from './routes/schedule/$scheduleId/start'
import { Route as ScheduleScheduleIdExcerciseIndexRouteImport } from './routes/schedule/$scheduleId/excercise/index'
import { Route as ScheduleScheduleIdExcerciseExcerciseIdRouteImport } from './routes/schedule/$scheduleId/excercise/$excerciseId'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightIndexRoute = WeightIndexRouteImport.update({
  id: '/weight/',
  path: '/weight/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/food/',
  path: '/food/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleCreateRoute = ScheduleCreateRouteImport.update({
  id: '/schedule/create',
  path: '/schedule/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodFoodIdRoute = FoodFoodIdRouteImport.update({
  id: '/food/$foodId',
  path: '/food/$foodId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleScheduleIdIndexRoute = ScheduleScheduleIdIndexRouteImport.update({
  id: '/schedule/$scheduleId/',
  path: '/schedule/$scheduleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleScheduleIdStartRoute = ScheduleScheduleIdStartRouteImport.update({
  id: '/schedule/$scheduleId/start',
  path: '/schedule/$scheduleId/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleScheduleIdExcerciseIndexRoute =
  ScheduleScheduleIdExcerciseIndexRouteImport.update({
    id: '/schedule/$scheduleId/excercise/',
    path: '/schedule/$scheduleId/excercise/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScheduleScheduleIdExcerciseExcerciseIdRoute =
  ScheduleScheduleIdExcerciseExcerciseIdRouteImport.update({
    id: '/schedule/$scheduleId/excercise/$excerciseId',
    path: '/schedule/$scheduleId/excercise/$excerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/food/$foodId': typeof FoodFoodIdRoute
  '/schedule/create': typeof ScheduleCreateRoute
  '/food/': typeof FoodIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/weight/': typeof WeightIndexRoute
  '/schedule/$scheduleId/start': typeof ScheduleScheduleIdStartRoute
  '/schedule/$scheduleId/': typeof ScheduleScheduleIdIndexRoute
  '/schedule/$scheduleId/excercise/$excerciseId': typeof ScheduleScheduleIdExcerciseExcerciseIdRoute
  '/schedule/$scheduleId/excercise/': typeof ScheduleScheduleIdExcerciseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/food/$foodId': typeof FoodFoodIdRoute
  '/schedule/create': typeof ScheduleCreateRoute
  '/food': typeof FoodIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/weight': typeof WeightIndexRoute
  '/schedule/$scheduleId/start': typeof ScheduleScheduleIdStartRoute
  '/schedule/$scheduleId': typeof ScheduleScheduleIdIndexRoute
  '/schedule/$scheduleId/excercise/$excerciseId': typeof ScheduleScheduleIdExcerciseExcerciseIdRoute
  '/schedule/$scheduleId/excercise': typeof ScheduleScheduleIdExcerciseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/food/$foodId': typeof FoodFoodIdRoute
  '/schedule/create': typeof ScheduleCreateRoute
  '/food/': typeof FoodIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/weight/': typeof WeightIndexRoute
  '/schedule/$scheduleId/start': typeof ScheduleScheduleIdStartRoute
  '/schedule/$scheduleId/': typeof ScheduleScheduleIdIndexRoute
  '/schedule/$scheduleId/excercise/$excerciseId': typeof ScheduleScheduleIdExcerciseExcerciseIdRoute
  '/schedule/$scheduleId/excercise/': typeof ScheduleScheduleIdExcerciseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/report'
    | '/food/$foodId'
    | '/schedule/create'
    | '/food/'
    | '/schedule/'
    | '/weight/'
    | '/schedule/$scheduleId/start'
    | '/schedule/$scheduleId/'
    | '/schedule/$scheduleId/excercise/$excerciseId'
    | '/schedule/$scheduleId/excercise/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/report'
    | '/food/$foodId'
    | '/schedule/create'
    | '/food'
    | '/schedule'
    | '/weight'
    | '/schedule/$scheduleId/start'
    | '/schedule/$scheduleId'
    | '/schedule/$scheduleId/excercise/$excerciseId'
    | '/schedule/$scheduleId/excercise'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/report'
    | '/food/$foodId'
    | '/schedule/create'
    | '/food/'
    | '/schedule/'
    | '/weight/'
    | '/schedule/$scheduleId/start'
    | '/schedule/$scheduleId/'
    | '/schedule/$scheduleId/excercise/$excerciseId'
    | '/schedule/$scheduleId/excercise/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ReportRoute: typeof ReportRoute
  FoodFoodIdRoute: typeof FoodFoodIdRoute
  ScheduleCreateRoute: typeof ScheduleCreateRoute
  FoodIndexRoute: typeof FoodIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  WeightIndexRoute: typeof WeightIndexRoute
  ScheduleScheduleIdStartRoute: typeof ScheduleScheduleIdStartRoute
  ScheduleScheduleIdIndexRoute: typeof ScheduleScheduleIdIndexRoute
  ScheduleScheduleIdExcerciseExcerciseIdRoute: typeof ScheduleScheduleIdExcerciseExcerciseIdRoute
  ScheduleScheduleIdExcerciseIndexRoute: typeof ScheduleScheduleIdExcerciseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight/': {
      id: '/weight/'
      path: '/weight'
      fullPath: '/weight/'
      preLoaderRoute: typeof WeightIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/': {
      id: '/food/'
      path: '/food'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/create': {
      id: '/schedule/create'
      path: '/schedule/create'
      fullPath: '/schedule/create'
      preLoaderRoute: typeof ScheduleCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$foodId': {
      id: '/food/$foodId'
      path: '/food/$foodId'
      fullPath: '/food/$foodId'
      preLoaderRoute: typeof FoodFoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId/': {
      id: '/schedule/$scheduleId/'
      path: '/schedule/$scheduleId'
      fullPath: '/schedule/$scheduleId/'
      preLoaderRoute: typeof ScheduleScheduleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId/start': {
      id: '/schedule/$scheduleId/start'
      path: '/schedule/$scheduleId/start'
      fullPath: '/schedule/$scheduleId/start'
      preLoaderRoute: typeof ScheduleScheduleIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId/excercise/': {
      id: '/schedule/$scheduleId/excercise/'
      path: '/schedule/$scheduleId/excercise'
      fullPath: '/schedule/$scheduleId/excercise/'
      preLoaderRoute: typeof ScheduleScheduleIdExcerciseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId/excercise/$excerciseId': {
      id: '/schedule/$scheduleId/excercise/$excerciseId'
      path: '/schedule/$scheduleId/excercise/$excerciseId'
      fullPath: '/schedule/$scheduleId/excercise/$excerciseId'
      preLoaderRoute: typeof ScheduleScheduleIdExcerciseExcerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ReportRoute: ReportRoute,
  FoodFoodIdRoute: FoodFoodIdRoute,
  ScheduleCreateRoute: ScheduleCreateRoute,
  FoodIndexRoute: FoodIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  WeightIndexRoute: WeightIndexRoute,
  ScheduleScheduleIdStartRoute: ScheduleScheduleIdStartRoute,
  ScheduleScheduleIdIndexRoute: ScheduleScheduleIdIndexRoute,
  ScheduleScheduleIdExcerciseExcerciseIdRoute:
    ScheduleScheduleIdExcerciseExcerciseIdRoute,
  ScheduleScheduleIdExcerciseIndexRoute: ScheduleScheduleIdExcerciseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
