/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as ScheduleCreateRouteImport } from './routes/schedule/create'
import { Route as ScheduleScheduleIdIndexRouteImport } from './routes/schedule/$scheduleId/index'
import { Route as ScheduleScheduleIdStartRouteImport } from './routes/schedule/$scheduleId/start'
import { Route as ScheduleScheduleIdExcerciseIndexRouteImport } from './routes/schedule/$scheduleId/excercise/index'
import { Route as ScheduleScheduleIdExcerciseExcerciseIdRouteImport } from './routes/schedule/$scheduleId/excercise/$excerciseId'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleCreateRoute = ScheduleCreateRouteImport.update({
  id: '/schedule/create',
  path: '/schedule/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleScheduleIdIndexRoute = ScheduleScheduleIdIndexRouteImport.update({
  id: '/schedule/$scheduleId/',
  path: '/schedule/$scheduleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleScheduleIdStartRoute = ScheduleScheduleIdStartRouteImport.update({
  id: '/schedule/$scheduleId/start',
  path: '/schedule/$scheduleId/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleScheduleIdExcerciseIndexRoute =
  ScheduleScheduleIdExcerciseIndexRouteImport.update({
    id: '/schedule/$scheduleId/excercise/',
    path: '/schedule/$scheduleId/excercise/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScheduleScheduleIdExcerciseExcerciseIdRoute =
  ScheduleScheduleIdExcerciseExcerciseIdRouteImport.update({
    id: '/schedule/$scheduleId/excercise/$excerciseId',
    path: '/schedule/$scheduleId/excercise/$excerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/schedule/create': typeof ScheduleCreateRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/schedule/$scheduleId/start': typeof ScheduleScheduleIdStartRoute
  '/schedule/$scheduleId/': typeof ScheduleScheduleIdIndexRoute
  '/schedule/$scheduleId/excercise/$excerciseId': typeof ScheduleScheduleIdExcerciseExcerciseIdRoute
  '/schedule/$scheduleId/excercise/': typeof ScheduleScheduleIdExcerciseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/schedule/create': typeof ScheduleCreateRoute
  '/schedule': typeof ScheduleIndexRoute
  '/schedule/$scheduleId/start': typeof ScheduleScheduleIdStartRoute
  '/schedule/$scheduleId': typeof ScheduleScheduleIdIndexRoute
  '/schedule/$scheduleId/excercise/$excerciseId': typeof ScheduleScheduleIdExcerciseExcerciseIdRoute
  '/schedule/$scheduleId/excercise': typeof ScheduleScheduleIdExcerciseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/schedule/create': typeof ScheduleCreateRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/schedule/$scheduleId/start': typeof ScheduleScheduleIdStartRoute
  '/schedule/$scheduleId/': typeof ScheduleScheduleIdIndexRoute
  '/schedule/$scheduleId/excercise/$excerciseId': typeof ScheduleScheduleIdExcerciseExcerciseIdRoute
  '/schedule/$scheduleId/excercise/': typeof ScheduleScheduleIdExcerciseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/schedule/create'
    | '/schedule/'
    | '/schedule/$scheduleId/start'
    | '/schedule/$scheduleId/'
    | '/schedule/$scheduleId/excercise/$excerciseId'
    | '/schedule/$scheduleId/excercise/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/schedule/create'
    | '/schedule'
    | '/schedule/$scheduleId/start'
    | '/schedule/$scheduleId'
    | '/schedule/$scheduleId/excercise/$excerciseId'
    | '/schedule/$scheduleId/excercise'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/schedule/create'
    | '/schedule/'
    | '/schedule/$scheduleId/start'
    | '/schedule/$scheduleId/'
    | '/schedule/$scheduleId/excercise/$excerciseId'
    | '/schedule/$scheduleId/excercise/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ScheduleCreateRoute: typeof ScheduleCreateRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  ScheduleScheduleIdStartRoute: typeof ScheduleScheduleIdStartRoute
  ScheduleScheduleIdIndexRoute: typeof ScheduleScheduleIdIndexRoute
  ScheduleScheduleIdExcerciseExcerciseIdRoute: typeof ScheduleScheduleIdExcerciseExcerciseIdRoute
  ScheduleScheduleIdExcerciseIndexRoute: typeof ScheduleScheduleIdExcerciseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/create': {
      id: '/schedule/create'
      path: '/schedule/create'
      fullPath: '/schedule/create'
      preLoaderRoute: typeof ScheduleCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId/': {
      id: '/schedule/$scheduleId/'
      path: '/schedule/$scheduleId'
      fullPath: '/schedule/$scheduleId/'
      preLoaderRoute: typeof ScheduleScheduleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId/start': {
      id: '/schedule/$scheduleId/start'
      path: '/schedule/$scheduleId/start'
      fullPath: '/schedule/$scheduleId/start'
      preLoaderRoute: typeof ScheduleScheduleIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId/excercise/': {
      id: '/schedule/$scheduleId/excercise/'
      path: '/schedule/$scheduleId/excercise'
      fullPath: '/schedule/$scheduleId/excercise/'
      preLoaderRoute: typeof ScheduleScheduleIdExcerciseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId/excercise/$excerciseId': {
      id: '/schedule/$scheduleId/excercise/$excerciseId'
      path: '/schedule/$scheduleId/excercise/$excerciseId'
      fullPath: '/schedule/$scheduleId/excercise/$excerciseId'
      preLoaderRoute: typeof ScheduleScheduleIdExcerciseExcerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ScheduleCreateRoute: ScheduleCreateRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  ScheduleScheduleIdStartRoute: ScheduleScheduleIdStartRoute,
  ScheduleScheduleIdIndexRoute: ScheduleScheduleIdIndexRoute,
  ScheduleScheduleIdExcerciseExcerciseIdRoute:
    ScheduleScheduleIdExcerciseExcerciseIdRoute,
  ScheduleScheduleIdExcerciseIndexRoute: ScheduleScheduleIdExcerciseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
